version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-innodb
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

volumes:
  mysql-data: